### ISSUE TITLE
Missing dependencies in latest version

### ISSUE THREAD

**Issue by alizehctl** [teervo/bitwig-fedora#1]
I get this error when I try to install the latest build

```
❯ sudo rpm -i bitwig-studio-4.1.6-1.fc35.x86_64.rpm 
error: Failed dependencies:
	libxcb-icccm.so.4 is needed by bitwig-studio-4.1.6-1.fc35.x86_64
	libxcb-util.so.1 is needed by bitwig-studio-4.1.6-1.fc35.x86_64
	libxkbcommon.so.0 is needed by bitwig-studio-4.1.6-1.fc35.x86_64
	libxkbcommon.so.0(V_0.5.0) is needed by bitwig-studio-4.1.6-1.fc35.x86_64
```
I already have the packages `xcb-util xcb-util-wm libxkbcommon` installed, which were used by the previous version of BItwig (4.0.5-1). I guess the latest build requires newer versions of these packages?

**Comment by teervo** [comment]
Hi!

The dependencies should be automatically pulled in, if you use dnf instead of rpm. You might also be missing the i686 versions of the mentioned libraries -- Bitwig depends on both.

**Comment by alizehctl** [comment]
Installing with dnf worked! Thanks
