### ISSUE TITLE
Uninstalled Bitiwig using DNF, in trying to install beta file, I get build-id errors and a stat error

### ISSUE THREAD

**Issue by johnledezma34** [teervo/bitwig-fedora#2]
[k.txt](https://github.com/teervo/bitwig-fedora/files/8177946/k.txt)
Heres the log file I got when I tried it. Something to add, manually going into the RPM folder and installing it using dnf works. Is that a safe alternate way to install it or are the logs showing something bad?

**Comment by teervo** [comment]
Everything before the last line is just a warning. I'm not really sure what is happening there -- the mv command that errors out just moves the RPM from rpmbuild/... to the current directory. It is perfectly safe to install it.

**Comment by johnledezma34** [comment]
Thank you, it is working perfectly. Will close the issue
