### ISSUE TITLE
Dependencies in Bitwig 4.3

### ISSUE THREAD

**Issue by myuujiku** [teervo/bitwig-fedora#3]
I tried installing bitwig with this script and got the following error:

Error:
 Problem: conflicting requests
  - nothing provides libjpeg.so.8()(64bit) needed by bitwig-studio-4.3-1.fc36.x86_64
  - nothing provides libjpeg.so.8(LIBJPEG_8.0)(64bit) needed by bitwig-studio-4.3-1.fc36.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

Got this result on two different machines with very recent installations of Fedora 36 Workstation following these steps:
1. wget https://raw.githubusercontent.com/teervo/bitwig-fedora/main/bitwig-rpm.sh
2. chmod +x bitwig-rpm.sh
3. ./bitwig-rpm.sh
4. sudo dnf install bitwig-studio-4.3-1.fc36.x86_64.rpm

Did I do something wrong or is there an issue with the script/bitwig?
This is in theory the best way I found to install bitwig on fedora so far.
All the other scripts are a bit janky and quite outdated and the flatpak doesn't support yabridge.

**Comment by teervo** [comment]
Thanks for bringing this up!

I haven't installed 4.3 yet, so didn't run into it myself. But there is indeed an issue. As https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/ puts it: "The libjpeg coming with Fedora/CentOS project (libjpeg-turbo) only provides v6 implementation of JPEG (aka. libjpeg.so.62). This project is provided as dependencies for various other projects which need libjpeg.so.7, libjpeg.so.8, etc." So for Bitwig we now need to install libjpeg8 from this Copr repo as well.

You can do this by running

```
sudo dnf copr add aflyhorse/libjpeg
sudo dnf install libjpeg8
```

I'll update the documentation and the script in the next few days.

**Comment by myuujiku** [comment]
Sweet, just tried your fix and it works!
And thanks for the quick reply.

I'll close this issue for now.
