### ISSUE TITLE
F37 missing lib64jpeg8

### ISSUE THREAD

**Issue by TotalChaos05** [teervo/bitwig-fedora#4]
I just had to install it from rpmfind.net
[https://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/lib64jpeg8-2.1.4-1-omv4090.x86_64.rpm](https://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/lib64jpeg8-2.1.4-1-omv4090.x86_64.rpm)

**Comment by TotalChaos05** [comment]
maybe add it to the readme

**Comment by teervo** [comment]
@TotalChaos05 Thanks for the reminder! This was already reported ages ago, but I never found the 5 minutes to update the readme. Done!
