### ISSUE TITLE
Does not support spaces in PWD

### ISSUE THREAD

**Issue by saworden** [teervo/bitwig-fedora#6]
I cloned this repo into `/home/saworden/Bitwig Studio/bitwig-fedora`, entered the `bitwig-fedora` directory, and ran `./bitwig-rpm.sh`. It downloads the latest DEB, but then produces the following error when building the RPM:

`error: failed to stat /home/saworden/Bitwig Studio/bitwig-fedora/Studio/bitwig-fedora/build: No such file or directory`
 
It seems that something is getting messed up due to the folder `Bitwig Studio` causing `$PWD` to have a space in it. Moving `bitwig-fedora` into my home directory (where there are no spaces in the path at all) and running the script from there, it executed cleanly and produced the RPM as expected. 

As an attempt to fix the script, I tried strategically placing some `'` and `"` quotes whenever `$PWD` is used to make sure it is surrounded by quotes when it is passed as an argument, but I guess I am not fluent enough in Bash to get that working.

**Comment by teervo** [comment]
Thanks for reporting! I've made some changes that fix the issue. While my script also had some problems, rpmbuild refused to cooperate with spaces in the build root. I worked around it by moving it to its default location, ~/rpmbuild.
