### ISSUE TITLE
don't work on bazzite

### ISSUE THREAD

**Issue by mouarfff** [teervo/bitwig-fedora#8]
hello

when i launch the script, i have this :

lego@bazzite:~/Téléchargements$ ./bitwig-rpm.sh 
./bitwig-rpm.sh: ligne 7: erreur de syntaxe près du symbole inattendu « newline »
./bitwig-rpm.sh: ligne 7: `<!DOCTYPE html>'

**Comment by teervo** [comment]
The script is only tested on Fedora and might not work on any other distro. If you want to write a pull request to fix it, please do.
