### ISSUE TITLE
error: Missing build-id in /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/BUILDROOT/opt/bitwig-studio/bin/liblwjgl.so

### ISSUE THREAD

**Issue by indigomirage** [teervo/bitwig-fedora#9]
Hi there -

I've used this tool for the past few Bitwig dot releases with no issue, but for the first time, I got errors:

`Scanned 405 directories and 3880 files,
               processed 345 inodes,
               312 modified (312 replaced + 0 rewritten),
               0 unsupported format, 0 errors
Reading /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/SPECPARTS/rpm-debuginfo.specpart
Processing files: bitwig-studio-5.2.7-1.fc41.x86_64
error: Missing build-id in /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/BUILDROOT/opt/bitwig-studio/bin/liblwjgl.so
error: Missing build-id in /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/BUILDROOT/opt/bitwig-studio/lib/bitwig-studio/libsqlitejdbc.so
error: Generating build-id links failed

RPM build warnings:
    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from

RPM build errors:
    Missing build-id in /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/BUILDROOT/opt/bitwig-studio/bin/liblwjgl.so
    Missing build-id in /home/indigo/rpmbuild/BUILD/bitwig-studio-5.2.7-build/BUILDROOT/opt/bitwig-studio/lib/bitwig-studio/libsqlitejdbc.so
    Generating build-id links failed`

I'm not sure how best to remedy this?  Is there some additional build tool that needs to be installed?

(Very grateful for the tool either way - I'm sure this is just a minor hiccup)

**Comment by teervo** [comment]
Thanks for reporting!

It's still working in Fedora 40, so it's probably a change with the build tools themselves. I made some changes and hopefully resolved the issue -- it worked fine in a Fedora 41 VM in any case.

Please let me know if this didn't resolve it for you.

**Comment by indigomirage** [comment]
It works!  You are the best.  Thank you!
